spring:
  application:
    name: yum-ingredient-server

  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: always

  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


springdoc:
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/ingredients/v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  enable-spring-security: true