CREATE TABLE IF NOT EXISTS ingredient (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_freezed BOOLEAN NOT NULL,
    is_favorite BOOLEAN NOT NULL,
    category VARCHAR(100) NOT NULL,
    start_at TIMESTAMP(6) NOT NULL,
    end_at TIMESTAMP(6) NOT NULL
);