package com.example.yum_web_server.ingredient.enums

enum class IngredientCategory(desc : String) {
    beef("beef"),
    beer("beer"),
    bread("bread"),
    broccoli("broccoli"),
    cabbage("cabbage"),
    canned_goods("canned_goods"),
    canned_tuna("canned_tuna"),
    cheese("cheese"),
    chicken_breast("chicken_breast"),
    drink("drink"),
    dumpling("dumpling"),
    egg("egg"),
    fish("fish"),
    fork("fork"),
    garlic("garlic"),
    grape("grape"),
    green_onion("green_onion"),
    ice_cream("ice_cream"),
    instance_noodle("instance_noodle"),
    milk("milk"),
    mushroom("mushroom"),
    noodle("noodle"),
    nut("nut"),
    onion("onion"),
    pepper("pepper"),
    potato("potato"),
    processed_meat("processed_meat"),
    rice("rice"),
    seaweed("seaweed"),
    shrimp("shrimp"),
    soju("soju"),
    tomato("tomato"),
    topu("topu"),
}